language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt

  # JavaScript test requirements
  - sudo add-apt-repository -y ppa:chris-lea/node.js
  - sudo apt-get -y update
  - sudo apt-get -y install nodejs
  - sudo npm install -g grunt-cli
  - sudo npm install -g bower
  - sudo npm install
before_script:
  - bower install

# command to run tests
script:
  - nosetests



